// Generated by CoffeeScript 1.12.7
(function() {
  var authController, passport;

  passport = require('passport');

  authController = module.exports;

  authController.loginPage = function(req, res) {
    return res.render('login', {
      next: req.query.next
    });
  };

  authController.login = function(method) {
    return function(req, res, next) {
      req.info("Authenticating via " + method);
      return passport.authenticate(method, {
        successRedirect: req.body.next || '/account',
        failureRedirect: '/account/login'
      })(req, res, next);
    };
  };

  authController.logout = function(req, res) {
    req.logout();
    return res.redirect('/account/login');
  };

}).call(this);
